===
## Reference: https://docs.github.com/en/actions/guides/deploying-to-amazon-elastic-container-service?learn=deploy_to_the_cloud
## This workflow is triggered on pushes to the repository branch main/master.

name: CDK TypeScript CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

## Initializes environment variables for the workflow
## REGION: Deployment Region
env:
  REGION: ap-southeast-1

jobs:
  build:

    name: Build And Deploy
    ## This job runs on Ubuntu Linux
    runs-on: ubuntu-latest

    steps:
      ## Checkout code from git repo branch configured above, under folder $GITHUB_WORKSPACE.
      - name: Checkout
        uses: actions/checkout@v2
      ## Sets up AWS profile.
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}
          role-to-assume: ${{ secrets.CROSS_ACCOUNT_ROLE }}
          role-duration-seconds: 1200
          role-session-name: GitActionDeploymentSession
      ## Installs CDK and other prerequisites
      - name: Prerequisite Installation
        run: |
          sudo npm install -g aws-cdk@1.90.1
          cdk --version
          aws s3 ls
      ## Build and Deploy CDK application
      - name: Build & Deploy
        run: |
          cd $GITHUB_WORKSPACE
          ls -a
          chmod 700 deploy.sh
          ./deploy.sh
